### PR TITLE
fix: add distinct aggregation limit error messages

### LINKED ISSUE #249: Return clear error messages when aggregation limit exceeded
There are three distinct limits for aggregations, but we return the same error message for each of them

Need to make distinct error messages so response gives full information about which specific limit was exceeded

### PR DESCRIPTION
**Pull request by forshev**
# Description

Added separate error message for each of aggregation limits

Fixes #249

---

- [x] I have read and followed all requirements in [CONTRIBUTING.md](https://github.com/ozontech/seq-db/blob/main/.github/CONTRIBUTING.md);
- [ ] I used LLM/AI assistance to make this pull request;

If you have used LLM/AI assistance please provide model name and full prompt:

```
Model: {{model-name}}
Prompt: {{prompt}}
```

### CODE REVIEW

File: proxy/search/ingestor.go [hunk 1]
```diff
@@ -567,8 +567,14 @@ func (si *Ingestor) searchShard(
...
-			if errMessage == consts.ErrTooManyUniqValues.Error() {
-				return nil, source, fmt.Errorf("store forbids aggregation request: %w", consts.ErrTooManyUniqValues)
+			if errMessage == consts.ErrTooManyFieldTokens.Error() {
+				return nil, source, fmt.Errorf("store forbids aggregation request: %w", consts.ErrTooManyFieldTokens)
+			}
+			if errMessage == consts.ErrTooManyGroupTokens.Error() {
+				return nil, source, fmt.Errorf("store forbids aggregation request: %w", consts.ErrTooManyGroupTokens)
+			}
+			if errMessage == consts.ErrTooManyFractionTokens.Error() {
+				return nil, source, fmt.Errorf("store forbids aggregation request: %w", consts.ErrTooManyFractionTokens)
```
Comment (moflotas) [inline proxy/search/ingestor.go:577]: I believe this is old behaviour, which is no currently used (since, we migrated from string comparisons to protobuf error-codes) and we should remove this code

File: frac/processor/aggregator_test.go [hunk 2]
```diff
@@ -251,3 +252,37 @@ func TestSingleTreeCountAggregator(t *testing.T) {
 		r.Equal(hist.Total, result.SamplesByBin[token].Total)
 	}
 }
+
+func TestAggregatorLimitExceeded(t *testing.T) {
+	// For now input for this test is incorrect since we support
+	// aggregations only for `keyword` index type.
+	// Will be fixed in #310.
```
Comment (moflotas) [inline frac/processor/aggregator_test.go:259]: nit: maybe add `TODO` to not forget about removing this code

**Review by moflotas — CHANGES_REQUESTED** [review]

File: proxy/search/ingestor.go (hunk 1 above)
Comment (moflotas) [reply proxy/search/ingestor.go:577]: discussed internally and decided to make those changes separately

**Review by moflotas — APPROVED** [review]
